apiVersion: v1
kind: Endpoints
metadata:
  name: petclinic-db
subsets:
  - addresses:
      - ip: 192.168.5.14
    ports:
      - port: 3306
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP